name: cartilhadeamamentacao
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_launcher_icons: ^0.7.5
  characters: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/book.jpeg
    - images/collaboration.jpeg
    - images/hiring.jpg
    - images/questions.jpeg
    - images/golden.jpeg
    - images/covid.jpeg
    - images/avatar1.jpeg
    - images/avatar2.jpeg
    - images/avatar3.jpeg
    - images/avatar4.jpeg
    - images/avatar5.jpeg
    - images/avatar6.jpeg
    - images/fernanda.jpeg
    - images/andressa.jpeg
    - images/covid_page1.jpg
    - images/covid_page2.jpg
    - images/covid_page3.jpg
    - images/golden_page.jpg
    - images/pagina1.jpeg
    - images/pagina2.jpg
    - images/pagina3.jpg
    - images/pagina4.jpg
    - images/pagina5.jpg
    - images/pagina6.jpg
    - images/pagina7.jpg
    - images/pagina8.jpg
    - images/pagina9.jpg
    - images/pagina10.jpg
    - images/pagina11.jpg
    - images/pagina12.jpg
    - images/pagina13.jpg
    - images/pagina14.jpg
    - images/pagina15.jpg
    - images/pagina16.jpg
    - images/pagina17.jpg
    - images/pagina18.jpg
    - images/pagina19.jpg
    - images/pagina20.jpg
    - images/pagina21.jpg
    - images/pagina22.jpg
    - images/pagina23.jpg
    - images/pagina24.jpg
    - images/pagina25.jpg
    - images/pagina26.jpg
    - images/pagina27.jpg
    - images/pagina28.jpg
    - images/pagina29.jpg
    - images/pagina30.jpg
    - images/pagina31.jpg
    - images/pagina32.jpg
    - images/comment_page1.jpg
    - images/comment_page2.jpg
    - images/comment_page3.jpg
    - images/comment_page4.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: true
  ios: true
  image_path: "icons/iconeapp.png"
